version: "3.8"
services:
  dev:
    build: .
    ports:
      - 8000:3000
    env_file: .env.test
    command: npm start
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: amigosecreto
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    command: --character-set-server=utf8
    restart: always
    