-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 10:52:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema codigomoda_db_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codigomoda_db_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codigomoda_db_1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `codigomoda_db_1` ;

-- -----------------------------------------------------
-- Table `codigomoda_db_1`.`microcosmos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigomoda_db_1`.`microcosmos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codigomoda_db_1`.`fechas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigomoda_db_1`.`fechas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_endulzada` VARCHAR(45) NOT NULL,
  `fecha_descubrimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigomoda_db_1`.`gerencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigomoda_db_1`.`gerencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `grupos_id` INT NULL DEFAULT NULL,
  `fechas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gerencias_grupos_idx` (`grupos_id` ASC) VISIBLE,
  INDEX `fk_gerencias_fechas1_idx` (`fechas_id` ASC) VISIBLE,
  CONSTRAINT `fk_gerencias_grupos`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `codigomoda_db_1`.`microcosmos` (`id`),
  CONSTRAINT `fk_gerencias_fechas1`
    FOREIGN KEY (`fechas_id`)
    REFERENCES `codigomoda_db_1`.`fechas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codigomoda_db_1`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigomoda_db_1`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `contrasenia` VARCHAR(200) NOT NULL,
  `gerencias_id` INT NOT NULL,
  `rolUsuario` INT NULL DEFAULT NULL,
  `gustos` VARCHAR(200) NOT NULL,
  `disgusto` VARCHAR(200) NOT NULL,
  `alegrias` VARCHAR(200) NOT NULL,
  `amigoSecreto` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_gerencias1_idx` (`gerencias_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_gerencias1`
    FOREIGN KEY (`gerencias_id`)
    REFERENCES `codigomoda_db_1`.`gerencias` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
